### ISSUE TITLE
run_disamb.py 运行多个数据对不上，还有model加载的文件也没有上传，请更新

### ISSUE THREAD

**Issue by lubaowang** [HuuuNan/PLMs-in-Practical-KBQA#1]

**Comment by HuuuNan** [comment]
Hi,

@lubaowang 请问具体报错是什么

**Comment by lubaowang** [comment]
<img width="1040" alt="image" src="https://github.com/HuuuNan/PLMs-in-Practical-KBQA/assets/46172119/b1b4b0fb-516f-462c-b406-8fcee3fb60ef">
<img width="588" alt="截屏2023-05-25 17 57 46" src="https://github.com/HuuuNan/PLMs-in-Practical-KBQA/assets/46172119/2a3089b0-8656-4e26-aeff-debda4ce82e0">

缺少数据集上面那个，然后下面这个方法参数对不上

**Comment by lubaowang** [comment]
看下问题哈 @ZhishanQ @HuuuNan

**Comment by ZhishanQ** [comment]
Hello, currently our server where we store the code and data is experiencing some issues. Our server center is working on fixing it, and as soon as it's back to normal, we will promptly address the problem you raised. @lubaowang

**Comment by wuyike2000** [comment]
代码已更新。相关字典可以通过https://pan.baidu.com/s/155LUfVYca2UMXAyhBsfUuA?pwd=bdzs下载，已更新readme。

**Comment by lubaowang** [comment]
ok，peace and love
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月07日 16:33 |
| 收件人 | HuuuNan/PLMs-in-Practical-KBQA ***@***.***> |
| 抄送人 | ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [HuuuNan/PLMs-in-Practical-KBQA] run_disamb.py 运行多个数据对不上，还有model加载的文件也没有上传，请更新 (Issue #1) |

代码已更新。相关字典可以通过https://pan.baidu.com/s/155LUfVYca2UMXAyhBsfUuA?pwd=bdzs下载，已更新readme。
