### ISSUE TITLE
论文中的几个公式符号错误

### ISSUE THREAD

**Issue by lyconghk** [HuuuNan/PLMs-in-Practical-KBQA#5]
你好，
论文工作做得很扎实，阅读后收获不少。
但发现如下一些小问题：
一、论文中的一些公式符号错误
1.  Section 4.2.4, 第一段内容中 r \in R_a， 应该是 R_c ;
2. Section 4.2.3 公式(4)中的h_r和footnote 7里面的h有歧义，都用了同一个符号h，正文中表示向量，但footnote里面写成一个scalar;
3. Section 4.2.4 公式(5)中的符号S_r is not defined，原因可能是上面问题2的歧义造成的，我猜应该是input sequence进入PLM后取第11个token[CLS]的表示向量h_cls，再经过线性层W=nn.linear(h, M)，得到一个向量s，长度是M(即KG中关系种类的个数)，那么S_r就是对应那个分量的logit;
4. Section 4.3 第三段内容, 写成'Sentience Bert';
5. Section 4.3 公式(7), Score(q, r_i)，应该是Score(p, r_i).

Ethan

**Comment by HuuuNan** [comment]
Hi,

感谢你对我们工作感兴趣以及对论文中错误的指出，我们将会修正并更新。

Best,
Nan
